//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutorzyKsiazki
    {
        public int id_autKsiazki { get; set; }
        public Nullable<int> id_autor { get; set; }
        public Nullable<int> id_ksiazka { get; set; }
    
        public virtual Autorzy Autorzy { get; set; }
        public virtual Ksiazki Ksiazki { get; set; }
    }
}
