//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Czytelnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Czytelnik()
        {
            this.Wypozyczenia = new HashSet<Wypozyczenia>();
        }
        [Key]
        public int id_czytelnik { get; set; }
        [Required]
        [DisplayName("Imie")]
        public string imie { get; set; }
        [Required]
        [DisplayName("Nazwisko")]
        public string nazwisko { get; set; }
        [Required]
        [DisplayName("Kod")]
        public string kod { get; set; }
        [Required]
        [DisplayName("PESEL")]
        public string pesel { get; set; }
        [Required]
        [DisplayName("E-mail")]
        public string email { get; set; }
        [Required]
        [DisplayName("Kod pocztowy")]
        public string kod_pocztowy { get; set; }
        [Required]
        [DisplayName("Miasto")]
        public string miasto { get; set; }
        [Required]
        [DisplayName("Ulica")]
        public string ulica { get; set; }
        [Required]
        [DisplayName("Nr domu")]
        public Nullable<int> nr_domu { get; set; }
        [DisplayName("Nr mieszkania")]
        public Nullable<int> nr_mieszkania { get; set; }
        [Required]
        [DisplayName("Województwo")]
        public string wojewodztwo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
