//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egzemplarze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Egzemplarze()
        {
            this.WypozyczeniaKsiazki = new HashSet<WypozyczeniaKsiazki>();
        }
    
        public int id_egzemplarz { get; set; }
        public Nullable<int> id_ksiazka { get; set; }
        public string sygnatura { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> id_biblio { get; set; }
        public Nullable<int> czy_zamowiona { get; set; }
        public Nullable<int> komu { get; set; }
    
        public virtual Ksiazki Ksiazki { get; set; }
        public virtual Statusy Statusy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WypozyczeniaKsiazki> WypozyczeniaKsiazki { get; set; }
        public virtual Biblioteka Biblioteka { get; set; }
        public virtual Czytelnik Czytelnik { get; set; }
    }
}
